"""empty message

Revision ID: a4660d797590
Revises: 8e4887e03e3b
Create Date: 2020-11-25 04:21:26.669651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4660d797590'
down_revision = '8e4887e03e3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('id', sa.Integer(), nullable=False, primary_key=True))
    op.alter_column('Show', 'artist',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Show', 'venue',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Show', 'venue',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Show', 'artist',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('Show', 'id')
    # ### end Alembic commands ###
