"""empty message

Revision ID: e49e93fa8c53
Revises: a4660d797590
Create Date: 2020-11-25 04:59:43.854942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e49e93fa8c53'
down_revision = 'a4660d797590'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    print('hi')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    print('hello')    # ### end Alembic commands ###
